
.MODEL SMALL  ;REPRESENT THE SIZE OF CODE.THE CODE SIZE CAN BE SMALL,MEDIUM,LARGE.
.STACK 200H   ;THIS STACK SAME AS BASIC STACK. 200H MEANS 200 HEX SPACE FOR STACK.
.DATA         ;WHERE ALL VARIABLE WILL BE DECLARED.
.CODE         ;CODE SEGMENT.CONTAINS MAIN PROC,FUNCTION CALL,CUSTOM FUNCTION ETC.
     MAIN PROC ;SAME AS INT MAIN().
        ;STATEMENT
        
        
        ;STATEMENT
        
         MOV AH,4CH
         INT 21H 
        
     MAIN ENDP  ;REPRESENTS MAIN FUNCTION IS END.


END MAIN      ;REPRESENT THIS CODE IS END.SAME AS RETURN 0.